from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Literal

Side = Literal["buy", "sell"]


@dataclass
class Fill:
    """
    Execution fill generated by the execution engine.

    - symbol: ticker
    - side: "buy" or "sell"
    - size: number of shares
    - price: execution price
    - timestamp: when the fill occurred (UTC)
    """

    symbol: str
    side: Side
    size: float
    price: float
    timestamp: datetime

    @property
    def notional(self) -> float:
        """Signed notional of the fill."""
        sign = 1.0 if self.side == "buy" else -1.0
        return sign * self.size * self.price
